services:
  pep-service:
    build: ./pep-service
    ports:
      - "8081:8080"
    depends_on:
      - pdp-service
      - resource-service

  pdp-service:
    build: ./pdp-service
    ports:
      - "8082:8080"

  resource-service:
    build: ./resource-service
    ports:
      - "8083:8080"

  client-app:
    build: ./client-app
    ports:
      - "8080:8080"
    depends_on:
      - pep-service