@startuml
actor Nutzer as User
participant "client-app" as client
participant "pep-service" as pep
participant "pdp-service" as pdp
participant "resource-service" as resource

activate User
User -> client : Zeig mir das Buch mit der ID 1
activate client
client --> User: Aufforderung zur Authentifizierung
User -> client : Authentifizierungsdaten

client -> pep : GET /api/resource/book/1\nAuthenticationDTO
activate pep
pep -> pdp : POST /initiate\nInitialAuthDTO
activate pdp
pdp -> pdp: bewerte Authentifizierungsdaten\nermittle Anzahl Runden n
pdp -> pdp: eröffne neue Session
loop n times
    pdp --> pep : 200 OK\nWarte auf Commitment
    deactivate pdp
    pep --> client: 200 OK\nWarte auf Commitment
    deactivate pep
    client -> pep: POST /api/authenticate\nCommitment
    activate pep
    pep -> pdp: POST /authenticate\nCommitment
    activate pdp
    pdp -> pdp: speichere Commitment zur Runde
    pdp --> pep: 200 OK\nChallenge
    deactivate pdp
    pep --> client: 200 OK\nChallenge
    deactivate pep
    client -> pep: POST /api/authenticate\nResponse
    activate pep
    pep -> pdp: POST /authenticate\nResponse
    activate pdp
    pdp -> pdp: verifiziere Response
end
pdp --> pep: 200 OK\nStatus: Verified
deactivate pdp
pep -> resource: GET /book/1
activate resource
resource --> pep: 200 OK\nBook{"id": 1,...}
deactivate resource
pep --> client: 200 OK\nBook{"id": 1,...}
deactivate pep
client --> User: Book{"id": 1,...}
deactivate client
@enduml