@startuml
participant "client-app" as client
participant "pep-service" as pep
participant "pdp-service" as pdp
participant "resource-service" as resource

activate client

client -> pep : GET /api/resource/book/1\nAuthData: Commitment
activate pep
''TODO Which Method does the pep use to access the pdp? Always GET?
pep -> pdp : GET /book/1\nAuthData: Commitment
activate pdp
pdp -> pdp: PE: determine n
alt n=-1
    pdp -> pep : 403 Forbidden\nStatus: n=-1
    deactivate pdp
    pep -> client : 403 Forbidden\nStatus: n=-1
    deactivate pep
else n>=0
    loop n times
        activate pdp
        pdp -> pdp: check Auth
        pdp -> pep: 401 Unauthorized\nStatus: Challenge
        activate pep
        deactivate pdp
        pep -> client: 401 Unauthorized\nStatus: Challenge
        deactivate pep
        client -> pep: GET /api/resource/book/1\nAuthData: Response
        activate pep
        pep -> pdp: GET /book/1\nAuthData: Response
        activate pdp
        pdp -> pdp: verify Response
        pdp -> pep: 401 Unauthorized\nStatus: Complete
        deactivate pdp
        pep -> client: 401 Unauthorized\nStatus: Complete
        deactivate pep
        client -> pep: GET /api/resource/book/1\nAuthData: Commitment
        activate pep
        pep -> pdp: GET /book/1\nAuthData: Commitment
        deactivate pep
    end
    pdp -> pep: 200 OK\nStatus: Verified
    activate pep
    pep -> resource: GET /book/1
    activate resource
    resource -> pep: 200 OK\nBook Data
    deactivate resource
    pep -> client: 200 OK\nBook Data
    deactivate pep
end
deactivate client
@enduml