@startuml
participant "client-app" as client
participant "pep-service" as pep
participant "pdp-service" as pdp

activate client
client -> pep : GET /auth/mod
activate pep
pep -> pdp : GET /mod
activate pdp
pdp -> pep : 200 OK\nmodulo m
deactivate pdp
pep -> client : 200 OK\nmodulo m
deactivate pep

note over client : v = s² mod m

client -> pep : POST /auth/register\nUserDTO
'\n{\n  "username": "alice",\n  "secret": "1234567890"\n}
activate pep
pep -> pdp : POST /register\nUserDTO
activate pdp
pdp -> pep : 200 OK
deactivate pdp
pep -> client : 200 OK
deactivate pep

deactivate client
@enduml